global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'buddy-api'
    static_configs:
      - targets: ['buddy-api:8000']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
